package require -exact qsys 15.0
set_module_property NAME sample_buffer_internal
set_module_property VERSION 1.0
set_module_property INTERNAL true
set_module_property GROUP HLS
set_module_property DISPLAY_NAME sample_buffer_internal
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_assignment hls.cosim.name {sample_buffer}

#### Synthesis fileset
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sample_buffer_internal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_package.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library_package.vhd
add_fileset_file dspba_library.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library.vhd
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file sample_buffer_function_wrapper.vhd VHDL PATH ip/sample_buffer_function_wrapper.vhd
add_fileset_file sample_buffer_function.vhd VHDL PATH ip/sample_buffer_function.vhd
add_fileset_file bb_sample_buffer_B2_sr_1.vhd VHDL PATH ip/bb_sample_buffer_B2_sr_1.vhd
add_fileset_file bb_sample_buffer_B3_sr_0.vhd VHDL PATH ip/bb_sample_buffer_B3_sr_0.vhd
add_fileset_file bb_sample_buffer_B0_runOnce.vhd VHDL PATH ip/bb_sample_buffer_B0_runOnce.vhd
add_fileset_file bb_sample_buffer_B0_runOnce_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B0_runOnce_stall_region.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_sample_buffer0.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_sample_buffer0.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_sample_buffer_reg.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_sample_buffer_reg.vhd
add_fileset_file i_acl_push_i1_wt_limpush_sample_buffer2.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_sample_buffer2.vhd
add_fileset_file i_acl_push_i1_wt_limpush_sample_buffer_reg.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_sample_buffer_reg.vhd
add_fileset_file sample_buffer_B0_runOnce_merge_reg.vhd VHDL PATH ip/sample_buffer_B0_runOnce_merge_reg.vhd
add_fileset_file sample_buffer_B0_runOnce_branch.vhd VHDL PATH ip/sample_buffer_B0_runOnce_branch.vhd
add_fileset_file sample_buffer_B0_runOnce_merge.vhd VHDL PATH ip/sample_buffer_B0_runOnce_merge.vhd
add_fileset_file bb_sample_buffer_B1_start.vhd VHDL PATH ip/bb_sample_buffer_B1_start.vhd
add_fileset_file bb_sample_buffer_B1_start_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B1_start_stall_region.vhd
add_fileset_file i_iord_bl_do_unnamed_sample_buffer1_sample_buffer14.vhd VHDL PATH ip/i_iord_bl_do_unnamed_sample_buffer1_sample_buffer14.vhd
add_fileset_file i_sfc_c0_wt_entry_sample_buffer_c0_enter_sample_buffer.vhd VHDL PATH ip/i_sfc_c0_wt_entry_sample_buffer_c0_enter_sample_buffer.vhd
add_fileset_file i_acl_sfc_exit_c0_wt_entry_sample_bufferA0Z_sample_buffer10.vhd VHDL PATH ip/i_acl_sfc_exit_c0_wt_entry_sample_bufferA0Z_sample_buffer10.vhd
add_fileset_file i_sfc_logic_c0_wt_entry_sample_buffer_c0A0Zr_sample_buffer4.vhd VHDL PATH ip/i_sfc_logic_c0_wt_entry_sample_buffer_c0A0Zr_sample_buffer4.vhd
add_fileset_file i_acl_pipeline_keep_going8_sample_buffer6.vhd VHDL PATH ip/i_acl_pipeline_keep_going8_sample_buffer6.vhd
add_fileset_file i_acl_push_i1_notexitcond9_sample_buffer8.vhd VHDL PATH ip/i_acl_push_i1_notexitcond9_sample_buffer8.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_sample_buffer12.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_sample_buffer12.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_sample_buffer_reg.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_sample_buffer_reg.vhd
add_fileset_file i_ffwd_src_unnamed_sample_buffer2_sample_buffer17.vhd VHDL PATH ip/i_ffwd_src_unnamed_sample_buffer2_sample_buffer17.vhd
add_fileset_file i_ffwd_src_unnamed_sample_buffer3_sample_buffer21.vhd VHDL PATH ip/i_ffwd_src_unnamed_sample_buffer3_sample_buffer21.vhd
add_fileset_file sample_buffer_B1_start_merge_reg.vhd VHDL PATH ip/sample_buffer_B1_start_merge_reg.vhd
add_fileset_file sample_buffer_B1_start_branch.vhd VHDL PATH ip/sample_buffer_B1_start_branch.vhd
add_fileset_file sample_buffer_B1_start_merge.vhd VHDL PATH ip/sample_buffer_B1_start_merge.vhd
add_fileset_file bb_sample_buffer_B2.vhd VHDL PATH ip/bb_sample_buffer_B2.vhd
add_fileset_file bb_sample_buffer_B2_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B2_stall_region.vhd
add_fileset_file i_iowr_bl_sample_out_unnamed_sample_buffA0Z_sample_buffer74.vhd VHDL PATH ip/i_iowr_bl_sample_out_unnamed_sample_buffA0Z_sample_buffer74.vhd
add_fileset_file i_sfc_c0_0_ac_fixed_0ba_01_0_0_0_qeaa_m_A0Z11_sample_buffer.vhd VHDL PATH ip/i_sfc_c0_0_ac_fixed_0ba_01_0_0_0_qeaa_m_A0Z11_sample_buffer.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Z_sample_buffer73.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Z_sample_buffer73.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zffer78_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zffer78_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zer_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zer_full_detector.vhd
add_fileset_file i_sfc_logic_c0_0_ac_fixed_0ba_01_0_0_0_qA0Z_sample_buffer23.vhd VHDL PATH ip/i_sfc_logic_c0_0_ac_fixed_0ba_01_0_0_0_qA0Z_sample_buffer23.vhd
add_fileset_file i_acl_pipeline_keep_going_sample_buffer29.vhd VHDL PATH ip/i_acl_pipeline_keep_going_sample_buffer29.vhd
add_fileset_file i_acl_pop_i32_i_05_pop7_sample_buffer44.vhd VHDL PATH ip/i_acl_pop_i32_i_05_pop7_sample_buffer44.vhd
add_fileset_file i_acl_pop_i33_fpgaindvars_iv_pop6_sample_buffer42.vhd VHDL PATH ip/i_acl_pop_i33_fpgaindvars_iv_pop6_sample_buffer42.vhd
add_fileset_file i_acl_pop_i4_cleanups_pop9_sample_buffer25.vhd VHDL PATH ip/i_acl_pop_i4_cleanups_pop9_sample_buffer25.vhd
add_fileset_file i_acl_pop_i4_initerations_pop8_sample_buffer31.vhd VHDL PATH ip/i_acl_pop_i4_initerations_pop8_sample_buffer31.vhd
add_fileset_file i_acl_push_i1_lastiniteration_sample_buffer38.vhd VHDL PATH ip/i_acl_push_i1_lastiniteration_sample_buffer38.vhd
add_fileset_file i_acl_push_i1_notexitcond_sample_buffer68.vhd VHDL PATH ip/i_acl_push_i1_notexitcond_sample_buffer68.vhd
add_fileset_file i_acl_push_i32_i_05_push7_sample_buffer60.vhd VHDL PATH ip/i_acl_push_i32_i_05_push7_sample_buffer60.vhd
add_fileset_file i_acl_push_i33_fpgaindvars_iv_push6_sample_buffer63.vhd VHDL PATH ip/i_acl_push_i33_fpgaindvars_iv_push6_sample_buffer63.vhd
add_fileset_file i_acl_push_i4_cleanups_push9_sample_buffer71.vhd VHDL PATH ip/i_acl_push_i4_cleanups_push9_sample_buffer71.vhd
add_fileset_file i_acl_push_i4_initerations_push8_sample_buffer34.vhd VHDL PATH ip/i_acl_push_i4_initerations_push8_sample_buffer34.vhd
add_fileset_file i_ffwd_dst_cmp4_phi_decision2_xor2_sample_buffer65.vhd VHDL PATH ip/i_ffwd_dst_cmp4_phi_decision2_xor2_sample_buffer65.vhd
add_fileset_file i_ffwd_dst_cmp4_phi_decision2_xor3_sample_buffer58.vhd VHDL PATH ip/i_ffwd_dst_cmp4_phi_decision2_xor3_sample_buffer58.vhd
add_fileset_file i_ffwd_dst_cmp4_phi_decision2_xor4_sample_buffer49.vhd VHDL PATH ip/i_ffwd_dst_cmp4_phi_decision2_xor4_sample_buffer49.vhd
add_fileset_file i_ffwd_dst_unnamed_sample_buffer4_sample_buffer40.vhd VHDL PATH ip/i_ffwd_dst_unnamed_sample_buffer4_sample_buffer40.vhd
add_fileset_file i_load_unnamed_sample_buffer5_sample_buffer51.vhd VHDL PATH ip/i_load_unnamed_sample_buffer5_sample_buffer51.vhd
add_fileset_file i_syncbuf_sample_buffer_sync_buffer_sample_buffer46.vhd VHDL PATH ip/i_syncbuf_sample_buffer_sync_buffer_sample_buffer46.vhd
add_fileset_file sample_buffer_B2_merge_reg.vhd VHDL PATH ip/sample_buffer_B2_merge_reg.vhd
add_fileset_file sample_buffer_B2_branch.vhd VHDL PATH ip/sample_buffer_B2_branch.vhd
add_fileset_file sample_buffer_B2_merge.vhd VHDL PATH ip/sample_buffer_B2_merge.vhd
add_fileset_file bb_sample_buffer_B3.vhd VHDL PATH ip/bb_sample_buffer_B3.vhd
add_fileset_file bb_sample_buffer_B3_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B3_stall_region.vhd
add_fileset_file i_acl_push_i1_throttle_push_sample_buffer76.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_sample_buffer76.vhd
add_fileset_file i_acl_push_i1_throttle_push_sample_buffer_reg.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_sample_buffer_reg.vhd
add_fileset_file i_iowr_nb_return_unnamed_sample_buffer7_sample_buffer75.vhd VHDL PATH ip/i_iowr_nb_return_unnamed_sample_buffer7_sample_buffer75.vhd
add_fileset_file sample_buffer_B3_branch.vhd VHDL PATH ip/sample_buffer_B3_branch.vhd
add_fileset_file sample_buffer_B3_merge.vhd VHDL PATH ip/sample_buffer_B3_merge.vhd
add_fileset_file i_acl_pipeline_keep_going8_sample_buffer_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going8_sample_buffer_sr.vhd
add_fileset_file i_acl_pipeline_keep_going8_sample_buffer_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going8_sample_buffer_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going_sample_buffer_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going_sample_buffer_sr.vhd
add_fileset_file i_acl_pipeline_keep_going_sample_buffer_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going_sample_buffer_valid_fifo.vhd
add_fileset_file loop_limiter_sample_buffer0.vhd VHDL PATH ip/loop_limiter_sample_buffer0.vhd
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_mem1x.v SYSTEM_VERILOG PATH ip/acl_mem1x.v
add_fileset_file acl_mem_staging_reg.v SYSTEM_VERILOG PATH ip/acl_mem_staging_reg.v
add_fileset_file acl_ic_local_mem_router.v SYSTEM_VERILOG PATH ip/acl_ic_local_mem_router.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file sample_buffer_internal.v SYSTEM_VERILOG PATH sample_buffer_internal.v

#### Simulation fileset
add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL sample_buffer_internal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dspba_library_package.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library_package.vhd
add_fileset_file dspba_library.vhd VHDL PATH windows64/lib/dspba/Libraries/vhdl/base/dspba_library.vhd
add_fileset_file acl_data_fifo.v SYSTEM_VERILOG PATH ip/acl_data_fifo.v
add_fileset_file acl_fifo.v SYSTEM_VERILOG PATH ip/acl_fifo.v
add_fileset_file acl_ll_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_fifo.v
add_fileset_file acl_ll_ram_fifo.v SYSTEM_VERILOG PATH ip/acl_ll_ram_fifo.v
add_fileset_file acl_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_valid_fifo_counter.v
add_fileset_file acl_dspba_valid_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_dspba_valid_fifo_counter.v
add_fileset_file acl_staging_reg.v SYSTEM_VERILOG PATH ip/acl_staging_reg.v
add_fileset_file hld_fifo.sv SYSTEM_VERILOG PATH ip/hld_fifo.sv
add_fileset_file hld_fifo_zero_width.sv SYSTEM_VERILOG PATH ip/hld_fifo_zero_width.sv
add_fileset_file acl_high_speed_fifo.sv SYSTEM_VERILOG PATH ip/acl_high_speed_fifo.sv
add_fileset_file acl_low_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_low_latency_fifo.sv
add_fileset_file acl_zero_latency_fifo.sv SYSTEM_VERILOG PATH ip/acl_zero_latency_fifo.sv
add_fileset_file acl_fanout_pipeline.sv SYSTEM_VERILOG PATH ip/acl_fanout_pipeline.sv
add_fileset_file acl_std_synchronizer_nocut.v SYSTEM_VERILOG PATH ip/acl_std_synchronizer_nocut.v
add_fileset_file acl_tessellated_incr_decr_threshold.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_decr_threshold.sv
add_fileset_file acl_tessellated_incr_lookahead.sv SYSTEM_VERILOG PATH ip/acl_tessellated_incr_lookahead.sv
add_fileset_file acl_reset_handler.sv SYSTEM_VERILOG PATH ip/acl_reset_handler.sv
add_fileset_file acl_lfsr.sv SYSTEM_VERILOG PATH ip/acl_lfsr.sv
add_fileset_file acl_pop.v SYSTEM_VERILOG PATH ip/acl_pop.v
add_fileset_file acl_push.v SYSTEM_VERILOG PATH ip/acl_push.v
add_fileset_file acl_token_fifo_counter.v SYSTEM_VERILOG PATH ip/acl_token_fifo_counter.v
add_fileset_file acl_pipeline.v SYSTEM_VERILOG PATH ip/acl_pipeline.v
add_fileset_file acl_dspba_buffer.v SYSTEM_VERILOG PATH ip/acl_dspba_buffer.v
add_fileset_file acl_enable_sink.v SYSTEM_VERILOG PATH ip/acl_enable_sink.v
add_fileset_file st_top.v SYSTEM_VERILOG PATH ip/st_top.v
add_fileset_file acl_ffwdsrc.v SYSTEM_VERILOG PATH ip/acl_ffwdsrc.v
add_fileset_file lsu_top.v SYSTEM_VERILOG PATH ip/lsu_top.v
add_fileset_file lsu_permute_address.v SYSTEM_VERILOG PATH ip/lsu_permute_address.v
add_fileset_file lsu_pipelined.v SYSTEM_VERILOG PATH ip/lsu_pipelined.v
add_fileset_file lsu_enabled.v SYSTEM_VERILOG PATH ip/lsu_enabled.v
add_fileset_file lsu_basic_coalescer.v SYSTEM_VERILOG PATH ip/lsu_basic_coalescer.v
add_fileset_file lsu_simple.v SYSTEM_VERILOG PATH ip/lsu_simple.v
add_fileset_file lsu_streaming.v SYSTEM_VERILOG PATH ip/lsu_streaming.v
add_fileset_file lsu_burst_master.v SYSTEM_VERILOG PATH ip/lsu_burst_master.v
add_fileset_file lsu_bursting_load_stores.v SYSTEM_VERILOG PATH ip/lsu_bursting_load_stores.v
add_fileset_file lsu_non_aligned_write.v SYSTEM_VERILOG PATH ip/lsu_non_aligned_write.v
add_fileset_file lsu_read_cache.v SYSTEM_VERILOG PATH ip/lsu_read_cache.v
add_fileset_file lsu_atomic.v SYSTEM_VERILOG PATH ip/lsu_atomic.v
add_fileset_file lsu_prefetch_block.v SYSTEM_VERILOG PATH ip/lsu_prefetch_block.v
add_fileset_file lsu_wide_wrapper.v SYSTEM_VERILOG PATH ip/lsu_wide_wrapper.v
add_fileset_file lsu_streaming_prefetch.v SYSTEM_VERILOG PATH ip/lsu_streaming_prefetch.v
add_fileset_file acl_aligned_burst_coalesced_lsu.v SYSTEM_VERILOG PATH ip/acl_aligned_burst_coalesced_lsu.v
add_fileset_file acl_toggle_detect.v SYSTEM_VERILOG PATH ip/acl_toggle_detect.v
add_fileset_file acl_debug_mem.v SYSTEM_VERILOG PATH ip/acl_debug_mem.v
add_fileset_file lsu_burst_coalesced_pipelined_write.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_write.sv
add_fileset_file lsu_burst_coalesced_pipelined_read.sv SYSTEM_VERILOG PATH ip/lsu_burst_coalesced_pipelined_read.sv
add_fileset_file acl_fifo_stall_valid_lookahead.sv SYSTEM_VERILOG PATH ip/acl_fifo_stall_valid_lookahead.sv
add_fileset_file acl_full_detector.v SYSTEM_VERILOG PATH ip/acl_full_detector.v
add_fileset_file acl_loop_limiter.v SYSTEM_VERILOG PATH ip/acl_loop_limiter.v
add_fileset_file acl_reset_wire.v SYSTEM_VERILOG PATH ip/acl_reset_wire.v
add_fileset_file sample_buffer_function_wrapper.vhd VHDL PATH ip/sample_buffer_function_wrapper.vhd
add_fileset_file sample_buffer_function.vhd VHDL PATH ip/sample_buffer_function.vhd
add_fileset_file bb_sample_buffer_B2_sr_1.vhd VHDL PATH ip/bb_sample_buffer_B2_sr_1.vhd
add_fileset_file bb_sample_buffer_B3_sr_0.vhd VHDL PATH ip/bb_sample_buffer_B3_sr_0.vhd
add_fileset_file bb_sample_buffer_B0_runOnce.vhd VHDL PATH ip/bb_sample_buffer_B0_runOnce.vhd
add_fileset_file bb_sample_buffer_B0_runOnce_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B0_runOnce_stall_region.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_sample_buffer0.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_sample_buffer0.vhd
add_fileset_file i_acl_pop_i1_wt_limpop_sample_buffer_reg.vhd VHDL PATH ip/i_acl_pop_i1_wt_limpop_sample_buffer_reg.vhd
add_fileset_file i_acl_push_i1_wt_limpush_sample_buffer2.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_sample_buffer2.vhd
add_fileset_file i_acl_push_i1_wt_limpush_sample_buffer_reg.vhd VHDL PATH ip/i_acl_push_i1_wt_limpush_sample_buffer_reg.vhd
add_fileset_file sample_buffer_B0_runOnce_merge_reg.vhd VHDL PATH ip/sample_buffer_B0_runOnce_merge_reg.vhd
add_fileset_file sample_buffer_B0_runOnce_branch.vhd VHDL PATH ip/sample_buffer_B0_runOnce_branch.vhd
add_fileset_file sample_buffer_B0_runOnce_merge.vhd VHDL PATH ip/sample_buffer_B0_runOnce_merge.vhd
add_fileset_file bb_sample_buffer_B1_start.vhd VHDL PATH ip/bb_sample_buffer_B1_start.vhd
add_fileset_file bb_sample_buffer_B1_start_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B1_start_stall_region.vhd
add_fileset_file i_iord_bl_do_unnamed_sample_buffer1_sample_buffer14.vhd VHDL PATH ip/i_iord_bl_do_unnamed_sample_buffer1_sample_buffer14.vhd
add_fileset_file i_sfc_c0_wt_entry_sample_buffer_c0_enter_sample_buffer.vhd VHDL PATH ip/i_sfc_c0_wt_entry_sample_buffer_c0_enter_sample_buffer.vhd
add_fileset_file i_acl_sfc_exit_c0_wt_entry_sample_bufferA0Z_sample_buffer10.vhd VHDL PATH ip/i_acl_sfc_exit_c0_wt_entry_sample_bufferA0Z_sample_buffer10.vhd
add_fileset_file i_sfc_logic_c0_wt_entry_sample_buffer_c0A0Zr_sample_buffer4.vhd VHDL PATH ip/i_sfc_logic_c0_wt_entry_sample_buffer_c0A0Zr_sample_buffer4.vhd
add_fileset_file i_acl_pipeline_keep_going8_sample_buffer6.vhd VHDL PATH ip/i_acl_pipeline_keep_going8_sample_buffer6.vhd
add_fileset_file i_acl_push_i1_notexitcond9_sample_buffer8.vhd VHDL PATH ip/i_acl_push_i1_notexitcond9_sample_buffer8.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_sample_buffer12.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_sample_buffer12.vhd
add_fileset_file i_acl_pop_i1_throttle_pop_sample_buffer_reg.vhd VHDL PATH ip/i_acl_pop_i1_throttle_pop_sample_buffer_reg.vhd
add_fileset_file i_ffwd_src_unnamed_sample_buffer2_sample_buffer17.vhd VHDL PATH ip/i_ffwd_src_unnamed_sample_buffer2_sample_buffer17.vhd
add_fileset_file i_ffwd_src_unnamed_sample_buffer3_sample_buffer21.vhd VHDL PATH ip/i_ffwd_src_unnamed_sample_buffer3_sample_buffer21.vhd
add_fileset_file sample_buffer_B1_start_merge_reg.vhd VHDL PATH ip/sample_buffer_B1_start_merge_reg.vhd
add_fileset_file sample_buffer_B1_start_branch.vhd VHDL PATH ip/sample_buffer_B1_start_branch.vhd
add_fileset_file sample_buffer_B1_start_merge.vhd VHDL PATH ip/sample_buffer_B1_start_merge.vhd
add_fileset_file bb_sample_buffer_B2.vhd VHDL PATH ip/bb_sample_buffer_B2.vhd
add_fileset_file bb_sample_buffer_B2_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B2_stall_region.vhd
add_fileset_file i_iowr_bl_sample_out_unnamed_sample_buffA0Z_sample_buffer74.vhd VHDL PATH ip/i_iowr_bl_sample_out_unnamed_sample_buffA0Z_sample_buffer74.vhd
add_fileset_file i_sfc_c0_0_ac_fixed_0ba_01_0_0_0_qeaa_m_A0Z11_sample_buffer.vhd VHDL PATH ip/i_sfc_c0_0_ac_fixed_0ba_01_0_0_0_qeaa_m_A0Z11_sample_buffer.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Z_sample_buffer73.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Z_sample_buffer73.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zffer78_data_fifo.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zffer78_data_fifo.vhd
add_fileset_file i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zer_full_detector.vhd VHDL PATH ip/i_acl_sfc_exit_c0_0_ac_fixed_0ba_01_0_0_A0Zer_full_detector.vhd
add_fileset_file i_sfc_logic_c0_0_ac_fixed_0ba_01_0_0_0_qA0Z_sample_buffer23.vhd VHDL PATH ip/i_sfc_logic_c0_0_ac_fixed_0ba_01_0_0_0_qA0Z_sample_buffer23.vhd
add_fileset_file i_acl_pipeline_keep_going_sample_buffer29.vhd VHDL PATH ip/i_acl_pipeline_keep_going_sample_buffer29.vhd
add_fileset_file i_acl_pop_i32_i_05_pop7_sample_buffer44.vhd VHDL PATH ip/i_acl_pop_i32_i_05_pop7_sample_buffer44.vhd
add_fileset_file i_acl_pop_i33_fpgaindvars_iv_pop6_sample_buffer42.vhd VHDL PATH ip/i_acl_pop_i33_fpgaindvars_iv_pop6_sample_buffer42.vhd
add_fileset_file i_acl_pop_i4_cleanups_pop9_sample_buffer25.vhd VHDL PATH ip/i_acl_pop_i4_cleanups_pop9_sample_buffer25.vhd
add_fileset_file i_acl_pop_i4_initerations_pop8_sample_buffer31.vhd VHDL PATH ip/i_acl_pop_i4_initerations_pop8_sample_buffer31.vhd
add_fileset_file i_acl_push_i1_lastiniteration_sample_buffer38.vhd VHDL PATH ip/i_acl_push_i1_lastiniteration_sample_buffer38.vhd
add_fileset_file i_acl_push_i1_notexitcond_sample_buffer68.vhd VHDL PATH ip/i_acl_push_i1_notexitcond_sample_buffer68.vhd
add_fileset_file i_acl_push_i32_i_05_push7_sample_buffer60.vhd VHDL PATH ip/i_acl_push_i32_i_05_push7_sample_buffer60.vhd
add_fileset_file i_acl_push_i33_fpgaindvars_iv_push6_sample_buffer63.vhd VHDL PATH ip/i_acl_push_i33_fpgaindvars_iv_push6_sample_buffer63.vhd
add_fileset_file i_acl_push_i4_cleanups_push9_sample_buffer71.vhd VHDL PATH ip/i_acl_push_i4_cleanups_push9_sample_buffer71.vhd
add_fileset_file i_acl_push_i4_initerations_push8_sample_buffer34.vhd VHDL PATH ip/i_acl_push_i4_initerations_push8_sample_buffer34.vhd
add_fileset_file i_ffwd_dst_cmp4_phi_decision2_xor2_sample_buffer65.vhd VHDL PATH ip/i_ffwd_dst_cmp4_phi_decision2_xor2_sample_buffer65.vhd
add_fileset_file i_ffwd_dst_cmp4_phi_decision2_xor3_sample_buffer58.vhd VHDL PATH ip/i_ffwd_dst_cmp4_phi_decision2_xor3_sample_buffer58.vhd
add_fileset_file i_ffwd_dst_cmp4_phi_decision2_xor4_sample_buffer49.vhd VHDL PATH ip/i_ffwd_dst_cmp4_phi_decision2_xor4_sample_buffer49.vhd
add_fileset_file i_ffwd_dst_unnamed_sample_buffer4_sample_buffer40.vhd VHDL PATH ip/i_ffwd_dst_unnamed_sample_buffer4_sample_buffer40.vhd
add_fileset_file i_load_unnamed_sample_buffer5_sample_buffer51.vhd VHDL PATH ip/i_load_unnamed_sample_buffer5_sample_buffer51.vhd
add_fileset_file i_syncbuf_sample_buffer_sync_buffer_sample_buffer46.vhd VHDL PATH ip/i_syncbuf_sample_buffer_sync_buffer_sample_buffer46.vhd
add_fileset_file sample_buffer_B2_merge_reg.vhd VHDL PATH ip/sample_buffer_B2_merge_reg.vhd
add_fileset_file sample_buffer_B2_branch.vhd VHDL PATH ip/sample_buffer_B2_branch.vhd
add_fileset_file sample_buffer_B2_merge.vhd VHDL PATH ip/sample_buffer_B2_merge.vhd
add_fileset_file bb_sample_buffer_B3.vhd VHDL PATH ip/bb_sample_buffer_B3.vhd
add_fileset_file bb_sample_buffer_B3_stall_region.vhd VHDL PATH ip/bb_sample_buffer_B3_stall_region.vhd
add_fileset_file i_acl_push_i1_throttle_push_sample_buffer76.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_sample_buffer76.vhd
add_fileset_file i_acl_push_i1_throttle_push_sample_buffer_reg.vhd VHDL PATH ip/i_acl_push_i1_throttle_push_sample_buffer_reg.vhd
add_fileset_file i_iowr_nb_return_unnamed_sample_buffer7_sample_buffer75.vhd VHDL PATH ip/i_iowr_nb_return_unnamed_sample_buffer7_sample_buffer75.vhd
add_fileset_file sample_buffer_B3_branch.vhd VHDL PATH ip/sample_buffer_B3_branch.vhd
add_fileset_file sample_buffer_B3_merge.vhd VHDL PATH ip/sample_buffer_B3_merge.vhd
add_fileset_file i_acl_pipeline_keep_going8_sample_buffer_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going8_sample_buffer_sr.vhd
add_fileset_file i_acl_pipeline_keep_going8_sample_buffer_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going8_sample_buffer_valid_fifo.vhd
add_fileset_file i_acl_pipeline_keep_going_sample_buffer_sr.vhd VHDL PATH ip/i_acl_pipeline_keep_going_sample_buffer_sr.vhd
add_fileset_file i_acl_pipeline_keep_going_sample_buffer_valid_fifo.vhd VHDL PATH ip/i_acl_pipeline_keep_going_sample_buffer_valid_fifo.vhd
add_fileset_file loop_limiter_sample_buffer0.vhd VHDL PATH ip/loop_limiter_sample_buffer0.vhd
add_fileset_file acl_avm_to_ic.v SYSTEM_VERILOG PATH ip/acl_avm_to_ic.v
add_fileset_file acl_mem1x.v SYSTEM_VERILOG PATH ip/acl_mem1x.v
add_fileset_file acl_mem_staging_reg.v SYSTEM_VERILOG PATH ip/acl_mem_staging_reg.v
add_fileset_file acl_ic_local_mem_router.v SYSTEM_VERILOG PATH ip/acl_ic_local_mem_router.v
add_fileset_file acl_ic_master_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_master_endpoint.v
add_fileset_file acl_arb_intf.v SYSTEM_VERILOG PATH ip/acl_arb_intf.v
add_fileset_file acl_ic_intf.v SYSTEM_VERILOG PATH ip/acl_ic_intf.v
add_fileset_file acl_ic_slave_endpoint.v SYSTEM_VERILOG PATH ip/acl_ic_slave_endpoint.v
add_fileset_file acl_ic_slave_rrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_rrp.v
add_fileset_file acl_ic_slave_wrp.v SYSTEM_VERILOG PATH ip/acl_ic_slave_wrp.v
add_fileset_file sample_buffer_internal.v SYSTEM_VERILOG PATH sample_buffer_internal.v

#### Primary clock for the component
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_assignment clock hls.cosim.name {$clock}
add_interface_port clock clock clk input 1

#### Primary reset for the component
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_assignment reset hls.cosim.name {$reset}
add_interface_port reset resetn reset_n input 1

#### Streaming interface for sample_out
add_interface sample_out avalon_streaming source
set_interface_property sample_out associatedClock clock
set_interface_property sample_out associatedReset reset
set_interface_property sample_out maxChannel 0
set_interface_property sample_out readyLatency 0
set_interface_property sample_out dataBitsPerSymbol 16
set_interface_property sample_out firstSymbolInHighOrderBits false
set_interface_assignment sample_out hls.cosim.name {sample_out}
add_interface_port sample_out sample_out_data data output 16
add_interface_port sample_out sample_out_ready ready input 1
add_interface_port sample_out sample_out_valid valid output 1

#### The component slave protocol interrupt request interface (done_irq)
add_interface irq interrupt end
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq associatedAddressablePoint avs_cra
set_interface_assignment irq hls.cosim.name {$irq}
add_interface_port irq done_irq irq output 1

#### Slave interface avs_cra
add_interface avs_cra avalon end
set_interface_property avs_cra ENABLED true
set_interface_property avs_cra associatedClock clock
set_interface_property avs_cra associatedReset reset
set_interface_property avs_cra addressAlignment DYNAMIC
set_interface_property avs_cra burstOnBurstBoundariesOnly false
set_interface_property avs_cra explicitAddressSpan 0
set_interface_property avs_cra holdTime 0
set_interface_property avs_cra isMemoryDevice false
set_interface_property avs_cra isNonVolatileStorage false
set_interface_property avs_cra linewrapBursts false
set_interface_property avs_cra maximumPendingReadTransactions 0
set_interface_property avs_cra printableDevice false
set_interface_property avs_cra readLatency 1
set_interface_property avs_cra readWaitTime 0
set_interface_property avs_cra setupTime 0
set_interface_property avs_cra timingUnits Cycles
set_interface_property avs_cra writeWaitTime 0
set_interface_assignment avs_cra hls.cosim.name {$cra}
add_interface_port avs_cra avs_cra_read read input 1
add_interface_port avs_cra avs_cra_write write input 1
add_interface_port avs_cra avs_cra_address address input 3
add_interface_port avs_cra avs_cra_writedata writedata input 64
add_interface_port avs_cra avs_cra_byteenable byteenable input 8
add_interface_port avs_cra avs_cra_readdata readdata output 64

#### Slave interface avs_sample_buffer
add_interface avs_sample_buffer avalon end
set_interface_property avs_sample_buffer ENABLED true
set_interface_property avs_sample_buffer associatedClock clock
set_interface_property avs_sample_buffer associatedReset reset
set_interface_property avs_sample_buffer addressAlignment DYNAMIC
set_interface_property avs_sample_buffer burstOnBurstBoundariesOnly false
set_interface_property avs_sample_buffer explicitAddressSpan 0
set_interface_property avs_sample_buffer holdTime 0
set_interface_property avs_sample_buffer isMemoryDevice false
set_interface_property avs_sample_buffer isNonVolatileStorage false
set_interface_property avs_sample_buffer linewrapBursts false
set_interface_property avs_sample_buffer maximumPendingReadTransactions 0
set_interface_property avs_sample_buffer printableDevice false
set_interface_property avs_sample_buffer readLatency 3
set_interface_property avs_sample_buffer readWaitTime 0
set_interface_property avs_sample_buffer setupTime 0
set_interface_property avs_sample_buffer timingUnits Cycles
set_interface_property avs_sample_buffer writeWaitTime 0
set_interface_assignment avs_sample_buffer hls.cosim.name {sample_buffer}
add_interface_port avs_sample_buffer avs_sample_buffer_read read input 1
add_interface_port avs_sample_buffer avs_sample_buffer_write write input 1
add_interface_port avs_sample_buffer avs_sample_buffer_address address input 9
add_interface_port avs_sample_buffer avs_sample_buffer_writedata writedata input 32
add_interface_port avs_sample_buffer avs_sample_buffer_byteenable byteenable input 4
add_interface_port avs_sample_buffer avs_sample_buffer_readdata readdata output 32

#### Quartus settings (QIP strings)
set_qip_strings { "set_instance_assignment -entity \"%entityName%\" -library \"%libraryName%\" -name AUTO_SHIFT_REGISTER_RECOGNITION OFF -to *_NO_SHIFT_REG*"  }
